add alt text and title to expand icon
illustrativemathematics/embeddable_content pull request #13
Opened 2021-07-16 02:14 UTC by tmaria17

- adds title and alt text to expand image icon
-  [ch 1659](https://app.clubhouse.io/illustrative-mathematics/story/1659/expand-image-icon-needs-alt-text)

2021-07-16 16:44 UTC, econnally approved these changes

2021-07-19 16:17 UTC, dylandechant approved these changes

2021-07-20 20:25 UTC, dylandechant requested changes
you will need to bump the version number on this again :)

edit: you may want to open a PR on iiab with the updated Gemfile.lock as well

2021-07-21 23:23 UTC, dylandechant approved these changes

2021-07-22 20:06 UTC, merged